export const UPDATE_TRANSACTIONS = "UPDATE_TRANSACTIONS";
export const GET_TRANSACTION = "UPDATE_TRANSACTIONS";
export const RESET_TRANSACTIONS = "UPDATE_TRANSACTIONS";
export const FETCHING_DATA = "FETCHING_DATA";
export const SET_CURRENT_BLOCK = "SET_CURRENT_BLOCK";
